CREATE DATABASE ECOMAPS;
USE ECOMAPS; 

CREATE TABLE USUARIO (
	CODIGO_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(250) NOT NULL,
    EMAIL_USUARIO VARCHAR(250) NOT NULL UNIQUE,
    CARGO_USUARIO VARCHAR(45)
);

CREATE TABLE TIPO_LOCALIDADE (
	CODIGO_TLOCALIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_TLOCALIDADE VARCHAR(80),
    DESCRICAO_TLOCALIDADE VARCHAR(250)
);

CREATE TABLE LOCALIDADE (
	CODIGO_LOCALIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LATITUDE_LOCALIDADE DECIMAL(9,6) NOT NULL,
    LONGITUDE_LOCALIDADE DECIMAL(9,6) NOT NULL,
    CODUSUARIO_LOCALIDADE INT NOT NULL,
    CTLOCALIDADE_LOCALIDADE INT NOT NULL,
    FOREIGN KEY (CODUSUARIO_LOCALIDADE) REFERENCES USUARIO(CODIGO_USUARIO),
    FOREIGN KEY (CTLOCALIDADE_LOCALIDADE) REFERENCES TIPO_LOCALIDADE(CODIGO_TLOCALIDADE)
);