CREATE DATABASE ECOMAPS;
USE ECOMAPS; 

CREATE TABLE USUARIO (
    CODIGO_USUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(250) NOT NULL,
    EMAIL_USUARIO VARCHAR(250) NOT NULL UNIQUE,
    CARGO_USUARIO VARCHAR(45) NOT NULL,
    CONSTRAINT chk_cargo CHECK (CARGO_USUARIO IN ('user', 'admin'))
);

ALTER TABLE USUARIO
ADD SENHA_USUARIO VARCHAR(255) NOT NULL;

ALTER TABLE USUARIO
ADD CPF_USUARIO VARCHAR(14) NOT NULL UNIQUE;

CREATE TABLE TIPO_LOCALIDADE (
    CODIGO_TLOCALIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_TLOCALIDADE VARCHAR(80),
    DESCRICAO_TLOCALIDADE VARCHAR(250)
);

CREATE TABLE LOCALIDADE (
    CODIGO_LOCALIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    LATITUDE_LOCALIDADE DECIMAL(9,6) NOT NULL,
    LONGITUDE_LOCALIDADE DECIMAL(9,6) NOT NULL,
    CODUSUARIO_LOCALIDADE INT NOT NULL,
    CTLOCALIDADE_LOCALIDADE INT NOT NULL,
    FOREIGN KEY (CODUSUARIO_LOCALIDADE) REFERENCES USUARIO(CODIGO_USUARIO),
    FOREIGN KEY (CTLOCALIDADE_LOCALIDADE) REFERENCES TIPO_LOCALIDADE(CODIGO_TLOCALIDADE)
);

ALTER TABLE LOCALIDADE
ADD NOME_LOCALIDADE VARCHAR(150) NOT NULL;
ADD DESCRICAO_LOCALIDADE VARCHAR(500);
ADD IMAGEM_LOCALIDADE VARCHAR(255);

CREATE TABLE IMAGEM_LOCALIDADE (
    CODIGO_IMAGEM INT AUTO_INCREMENT PRIMARY KEY,
    CAMINHO_IMAGEM VARCHAR(255) NOT NULL,
    CODLOCALIDADE_IMAGEM INT NOT NULL,
    FOREIGN KEY (CODLOCALIDADE_IMAGEM) REFERENCES LOCALIDADE(CODIGO_LOCALIDADE)
);


